apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hogwarts-bot
  namespace: hogwarts-bot
spec:
  selector:
    matchLabels:
      app: bot
  replicas: 1
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: sheepfunk/hogwarts-bot
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - name: secrets
          mountPath: "/app/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
           secretName: hogwarts-secrets